#!/bin/bash
set -euo pipefail

# Install Tailscale.
# Usage: /usr/local/installs/tailscale

export DEBIAN_FRONTEND=noninteractive

add-apt-repo tailscale \
    https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg \
    https://pkgs.tailscale.com/stable/ubuntu noble main

apt-get update
apt-get install -y --no-install-recommends tailscale
apt-get clean
rm -rf /var/lib/apt/lists/*
